// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeeiHSI88JgSjLL59HYOY73e3-cnXJu4o',
    appId: '1:894026970766:web:841feba7fa722289d3fbdf',
    messagingSenderId: '894026970766',
    projectId: 'flutter-projects-27840',
    authDomain: 'flutter-projects-27840.firebaseapp.com',
    storageBucket: 'flutter-projects-27840.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQJw2GHoG3xyge1EDnp1hj0f_Fl6KcV10',
    appId: '1:894026970766:android:b1b4a02757652fe8d3fbdf',
    messagingSenderId: '894026970766',
    projectId: 'flutter-projects-27840',
    storageBucket: 'flutter-projects-27840.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz7jBlKq38wk-i_xbY_g8pFQzWhWHX1Pw',
    appId: '1:894026970766:ios:c1260fb6ce2f865bd3fbdf',
    messagingSenderId: '894026970766',
    projectId: 'flutter-projects-27840',
    storageBucket: 'flutter-projects-27840.appspot.com',
    iosClientId: '894026970766-g6v64s1allcckq42q488a0kadur1r3a3.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz7jBlKq38wk-i_xbY_g8pFQzWhWHX1Pw',
    appId: '1:894026970766:ios:0a7ec4c5e75bf70dd3fbdf',
    messagingSenderId: '894026970766',
    projectId: 'flutter-projects-27840',
    storageBucket: 'flutter-projects-27840.appspot.com',
    iosClientId: '894026970766-eddkh7rmjfkf1th10jtdh8t0i71oqnrk.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushApp.RunnerTests',
  );
}
